 # Site Settings
baseurl: ""
url : "https://gauravchafe.github.io"

# Blog Settings
theme_settings :
  title : Gaurav Chafe
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/gaurav chafe white bg.png
    username : Gaurav Chafe
    description : An avid enthusiast of Marketing Automation with good experience of Salesforce and Pardot (Marketing Automation) end to end implementation and support. Enabling customers towards the 4th Industrial revolution of Digital transformation through automation of sales and marketing teams for high-performance, scalable adaption, and long-term success.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : Tranzevo, Senior Consultant
    skills : 
      - skill : Salesforce Pardot
        value : 85  # Percent value
      - skill : Salesforce Sales Cloud
        value : 55  # Percent value
      - skill : Salesforce Service Cloud
        value : 35  # Percent value
      - skill : Salesforce Community Cloud
        value : 75  # Percent value
      - skill : HTML5 & CSS
        value : 85  # Percent value
      
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  https://in.linkedin.com/in/gauravchafe 
    github: gauravchafe
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: https://twitter.com/gauravchafe
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
